name: autopYT
channels:
  - conda-forge
dependencies:
  - bzip2
  - ca-certificates
  - libexpat
  - libffi
  - libsqlite
  - libzlib
  - ncurses
  - openssl
  - pip
  - python
  - readline
  - setuptools
  - tk
  - tzdata
  - wheel
  - xz
  - pip:
    - brotli
    - cachetools
    - certifi
    - charset-normalizer
    - google-api-core
    - google-api-python-client
    - google-auth
    - google-auth-httplib2
    - google-auth-oauthlib
    - googleapis-common-protos
    - httplib2
    - idna
    - mutagen
    - oauthlib
    - pip
    - proto-plus
    - protobuf
    - pyasn1
    - pyasn1-modules
    - pycryptodomex
    - pyparsing
    - python-dotenv
    - requests
    - requests-oauthlib
    - rsa
    - uritemplate
    - urllib3
    - websockets
    - yt-dlp
